// whats-for-dinner-react/src/components/appnav/index.tsx
import * as React from 'react';

export const AppNav: React.StatelessComponent = () => {
    const nav = (
        <nav className="navbar navbar-expand-lg navbar-light bg-light">
            <div className="navbar-brand">What's For Dinner?</div>
            <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span className="navbar-toggler-icon"></span>
            </button>
            <div className="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div className="navbar-nav">
                    <a href="/" className="nav-link">Home</a>
                    <a href="/recipes" className="nav-link">Recipes</a>
                    <a href="/grocerylist" className="nav-link">Grocery List</a>
                </div>
            </div>
        </nav>
    );

    return nav;
}

// whats-for-dinner-vue/src/components/AppNav.vue
<template>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="navbar-brand">What's For Dinner?</div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <router-link to="/" class="nav-link">Home</router-link>
                <router-link to="/recipes" class="nav-link">Recipes</router-link>
                <router-link to="/grocerylist" class="nav-link">Grocery List</router-link>
            </div>
        </div>
    </nav>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';

@Component
export default class AppNav extends Vue {
}
</script>
