// whats-for-dinner-react/src/pages/recipes/index.tsx
import * as React from 'react';
import RecipeList from '../../components/recipelist';

export const RecipesPage: React.StatelessComponent = (props: any) => {
  const handleRecipeClicked = (recipeId: number|null) => {
    if(recipeId) {
      props.history.push(`/recipes/item/${recipeId}`);
    }
  }

    const nav = (
      <div className="recipes-management">
        <a href="/recipes/item" className="btn btn-primary">Create New</a>
        <RecipeList recipeOnClick={handleRecipeClicked} />
      </div>
    );

    return nav;
}

// whats-for-dinner-vue/src/views/Recipes.vue
<template>
  <div class="recipes-management">
    <router-link to="/recipes/item" class="btn btn-primary">Create New</router-link>
    <RecipeList v-on:recipe-list-click="handleRecipeSelected"/>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';
import RecipeList from '@/components/RecipeList.vue'; // @ is an alias to /src
// import { mapMutations } from 'vuex';

@Component({
  components: {
    RecipeList
  }
})
export default class Home extends Vue {
  public handleRecipeSelected(recipeId: number) {
    this.$router.push(`/recipes/item/${recipeId}`);
  }
}
</script>
